### ISSUE TITLE
License, change GOOGLE INC. to GOOGLE LLC

### ISSUE THREAD

**Issue by Atheuz** [protocolbuffers/upb#1177]
In the license you have the line:

    THIS SOFTWARE IS PROVIDED BY GOOGLE INC. ``AS IS'' AND ANY EXPRESS OR IMPLIED

Should be?

    THIS SOFTWARE IS PROVIDED BY GOOGLE LLC ``AS IS'' AND ANY EXPRESS OR IMPLIED

https://github.com/protocolbuffers/upb/blob/main/LICENSE#L17

Seems like it was partially updated, but this was missed.

**Comment by coryan** [comment]
The policy guidance inside  Google is that new files get `LLC` while existing files need not be updated.
