### ISSUE TITLE
The way the utf8_range dependency gets included in upb cmake build is inconsistent with protobuf

### ISSUE THREAD

**Issue by jtattermusch** [protocolbuffers/upb#1201]
The way the utf8_range dependency gets included in the protobuf build (see b/266069601) has recently changed to including it in the protobuf codebase as a subtree (https://github.com/protocolbuffers/protobuf/pull/11608). That seems to have solved grpc's problem with transitive submodule dependencies, but now we realized that upb also depends on utf8_range (and does that via fetch_content in the cmake build).
Because of the way we include upb in the grpc's cmake build (we scrape the list of sources and headers from upb's bazel build), the way upb depends on utf8_range doesn't work for us (since the utf8_range sources aren't available in the upb source).
Can upb also switch to including utf8_range as a git subtree (just a protobuf did)? (IMHO many of the arguments from b/266069601 still apply here).
Perhaps there are alternative solutions, but ideally the way utf8_range gets included in the build should be consistent between upb and protobuf, so that we don't have to invent 2 solutions for the same dependency.

**Comment by deannagarcia** [comment]
Maintaining utf_8 range as a subtree in upb is too much of a support burden for us. We don't want to have to maintain 2 copies of the library and keep them in sync.

We provide a [CMakeLists.txt](https://github.com/protocolbuffers/upb/blob/main/cmake/CMakeLists.txt), can you use that?

**Comment by jtattermusch** [comment]
FetchContent for utf8_range doesn't work for us since we need the utf8_range sources to be present on the disk for other build systems (which we use for building e.g. the grpc python or grpc ruby extensions - these have their own custom build systems and don't rely on cmake) - this is one of the reasons why we use git submodules for our non-bazel builds (cmake and other build systems).

Also, now I realized another problem. Since grpc depends on upb, which in turn depends on utf8_range,  and protobuf also depends on utf8_range, the build needs to setup so that utf8_range doesn't get built and linked twice - otherwise we're pretty much guaranteed to get symbol conflicts  (anyone who's using gRPC C++ in a project is 99.9% to also use protobuf).

So I think the only viable solution here is to expose utf8_range as a standalone library and then  both protobuf and upb take dependency on that library.  After that, gRPC will also take an explicit dependency on utf8_range (probably add a git submodule for utf8_range). Otherwise users will get utf8_range included twice (leading to ODR violations).

Btw, how important is the utf8_range dependency and what functionality it provides? I am wondering if it's worth all the extra trouble with adding a new dependency. Also, can we possibly make the utf8 library header-only? That might avoid the issue with symbol conflicts.

**Comment by deannagarcia** [comment]
We fixed this by adding a conditional to the cmake usage of utf8_range to only import it if it wasn't existing.
