### ISSUE TITLE
Unable to build on Alpine Linux

### ISSUE THREAD

**Issue by vthib** [protocolbuffers/upb#1212]
Trying to build the `//python/dist:binary_wheel` target on Alpine fails on this error:

```
Repository rule pip_repository defined at:
  /root/.cache/bazel/_bazel_root/9fabff63541097ed1dd428064ee5b4c7/external/rules_python/python/pip_install/pip_repository.bzl:474:33: in <toplevel>
ERROR: An error occurred during the fetch of repository 'pip_deps':
   Traceback (most recent call last):
        File "/root/.cache/bazel/_bazel_root/9fabff63541097ed1dd428064ee5b4c7/external/rules_python/python/pip_install/pip_repository.bzl", line 341, column 13, in _pip_repository_impl
                fail("rules_python failed: %s (%s)" % (result.stdout, result.stderr))
Error in fail: rules_python failed:  (src/main/tools/process-wrapper-legacy.cc:80: "execvp(/root/.cache/bazel/_bazel_root/9fabff63541097ed1dd428064ee5b4c7/external/system_python/interpreter, ...)": Exec format error
```

This is caused by the https://github.com/protocolbuffers/upb/commit/248ed86f2bfe6cf3dc7ffc69fa55cb488fd4a4ea commit, which creates an `interpreter` file containing `exec /.../python3 "$@"`. This file however is not executable as it is missing a shebang, hence the `exec format error` returned.

Adding a `#!/bin/sh` on top of this file fixes the issue, though I don't think this is the right fix.

**Comment by haberman** [comment]
> Adding a #!/bin/sh on top of this file fixes the issue, though I don't think this is the right fix.

What is wrong with this fix?

@mkruskal-google

**Comment by haberman** [comment]
> Why have an interpreter file containing `exec <path_to_python3> "$@" `and using this interpreter as the executable, instead of just using `<path_to_python3>` as the executable?

The actions will run in a sandboxed environment that may have a different `PATH`. The only way to respect the `$PATH` that Bazel was run under is to persist the full path of the preferred Python executable into a file that we can reliably reference from within the sandboxed environment.

I think adding `#!/bin/sh` is the right solution here. If it fails on some distro we can try to find a variant that is more widely portable.

**Comment by mkruskal-google** [comment]
I agree, I think the shebang is the correct solution here.  If it breaks on a linux distribution we support we should add tests and specialized handling for that, but this is consistent with scripts we use elsewhere already

**Comment by vthib** [comment]
@haberman I posted a PR to fix this, is it possible to take a look?
