### ISSUE TITLE
Segfault when not setting required field in message that's put into another message

### ISSUE THREAD

**Issue by FSX** [protocolbuffers/upb#1220]
Sorry, I found it a bit hard to make up a understandable title. Below is a minimal sample that triggers the segfault. It only happens when I put `Request` into `Message`.

I'm using Python 3.10.10 and protobuf 4.22.1. Let me know if you need more information.

Protobuf:

```
syntax = "proto2";

message Message
{
        optional Request request = 1;
}

message Request
{
        required int32 id = 1;
}
```

Python code:

```
from messages_pb2 import Message, Request

req = Request()
Message(request=req)
```

`protoc` command:

```
protoc --python_out=. messages.proto
```

**Comment by ericsalo** [comment]
The fix for this has been pushed to the main upb branch. I will close this issue once the corresponding unit test has also been pushed to the main protobuf branch.
