### ISSUE TITLE
upb-specific python setup in bazel breaks gRPC bazel build.

### ISSUE THREAD

**Issue by jtattermusch** [protocolbuffers/upb#1239]
Due to some changes in upb's bazel build related to setting up python environment, we'd need to modify gRPC's bazel build but it's unclear how.

When I keep our bazel build's WORKSPACE unmodified, after upgrading upb (to 22.x) I'm now getting an error:

```
# the //examples/python/multiprocessing:prime_proto_pb2 target is what triggers the problem
bazel build //examples/python/multiprocessing:prime_proto_pb2
INFO: Running bazel wrapper (see //tools/bazel for details), bazel version 5.3.0 will be used instead of system-wide bazel installation.
ERROR: /usr/local/google/home/jtattermusch/.cache/bazel/_bazel_jtattermusch/473402ebb46aca5e4ea9eb310c6f9e93/external/com_google_protobuf/BUILD.bazel:281:6: error loading package '@com_google_protobuf//python': Unable to find package for @pip_deps//:requirements.bzl: The repository '@pip_deps' could not be resolved: Repository '@pip_deps' is not defined. and referenced by '@com_google_protobuf//:protobuf_python'
ERROR: Analysis of target '//examples/python/multiprocessing:prime_proto_pb2' failed; build aborted: 

```

The prime_proto_pb2 is a `py_proto_library` target:
https://github.com/grpc/grpc/blob/625b3544e7ac14b3c2fb3d38dbf342f083926610/examples/python/multiprocessing/BUILD#L25

This is how protobuf itself has reacted to upb's bazel changes:
https://github.com/protocolbuffers/protobuf/commit/3bc50497eb1bf76bd7e34b548fa4c552e4f90131

I tried including something similar in gRPC's bazel WORKSPACE:
```
load("@upb//bazel:system_python.bzl", "system_python")
system_python(
    name = "system_python",
    minimum_python_version = "3.7",
)

load("@system_python//:pip.bzl", "pip_parse")
pip_parse(
    name="pip_deps",
    requirements = "@upb//python:requirements.txt",
    requirements_overrides = {
        "3.11": "@upb//python:requirements_311.txt",
    },
)
```

But that doesn't seem to work, and when trying to build with this patch, I'm getting:
```
ERROR: /usr/local/google/home/jtattermusch/.cache/bazel/_bazel_jtattermusch/473402ebb46aca5e4ea9eb310c6f9e93/external/com_google_protobuf/python/BUILD.bazel:54:20: in internal_copy_files_impl rule @com_google_protobuf//python:copied_wkt_proto_files: 
Traceback (most recent call last):
	File "/usr/local/google/home/jtattermusch/.cache/bazel/_bazel_jtattermusch/473402ebb46aca5e4ea9eb310c6f9e93/external/com_google_protobuf/python/internal.bzl", line 11, column 17, in _internal_copy_files_impl
		fail("Source does not start with %s: %s" %
Error in fail: Source does not start with src/: ../com_google_protobuf/src/google/protobuf/any.proto
ERROR: /usr/local/google/home/jtattermusch/.cache/bazel/_bazel_jtattermusch/473402ebb46aca5e4ea9eb310c6f9e93/external/com_google_protobuf/python/BUILD.bazel:54:20: Analysis of target '@com_google_protobuf//python:copied_wkt_proto_files' failed
ERROR: Analysis of target '//examples/python/multiprocessing:prime_proto_pb2' failed; build aborted: 
```

So I have 2 problems:
- I'm unable to get certain targets in our bazel build to work (presumably it's those that use https://github.com/grpc/grpc/blob/master/bazel/python_rules.bzl)
- We don't necessarily want details about how upb configures python (e.g. https://github.com/protocolbuffers/upb/blob/main/bazel/system_python.bzl) to leak into our build (and potentially to the build of our users?)

**Comment by jtattermusch** [comment]
CC @haberman @deannagarcia @mkruskal-google  this is one of the blockers for grpc's upgrade to protobuf 22.x

**Comment by jtattermusch** [comment]
CC @gnossen @veblush  help/advice is welcome.

**Comment by deannagarcia** [comment]
This issue should be resolved with https://github.com/protocolbuffers/protobuf/commit/13833b1df01b811c6b0a3a2c83864579d740050f and some follow-up changes that are already submitted.

**Comment by jtattermusch** [comment]
FTR, looks like grpc/grpc stopped requiring the patch here: https://github.com/grpc/grpc/pull/32914/files#diff-71613c5804416c5789b4eca93269d89a16bb45071456c8212bb4851fbfcd4851L265
