### ISSUE TITLE
Memory leak in ByteSize with upb protobuf backend

### ISSUE THREAD

**Issue by nikita-uvarov** [protocolbuffers/upb#1243]
**What version of protobuf and what language are you using?**
Language: Python
Version: protobuf==4.22.1

**Reproduce**
Run the following script with the latest protobuf==4.22.1 python package from PyPI:

```
import google.protobuf
from google.protobuf.type_pb2 import Type
from google.protobuf.source_context_pb2 import SourceContext

def print_rss():
    with open('/proc/self/status') as fp:
        print([line.strip() for line in fp.readlines() if line.startswith('RssAnon')][0])

if __name__ == '__main__':
    p = Type()

    for it in range(1000000):
        p.source_context.ByteSize()
    print_rss()

    for it in range(1000000):
        p.source_context.ByteSize()
    print_rss()

    print(f"pip package 'protobuf' version: {google.protobuf.__version__}")
    print(f"api_implementation.Type(): {google.protobuf.internal.api_implementation.Type()}")
```

Example output (docker python:3.8 image):
```
root@f38c7dfd34c4:/# python3 ./leak.py 
RssAnon:           83008 kB
RssAnon:          161152 kB
pip package 'protobuf' version: 4.22.1
api_implementation.Type(): upb
```

**Problem**
Repetetive calls to ByteSize cause anonymous memory usage to grow indefinitely. I suspect there is memory leak in implementation of ByteSize.

**Note**
This behaviour is not observed with the Python backend:
```
root@f38c7dfd34c4:/# PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python python3 ./leak.py 
RssAnon:            7656 kB
RssAnon:            7656 kB
pip package 'protobuf' version: 4.22.1
api_implementation.Type(): python
```

**Comment by flipk** [comment]
I came here to post the same issue. protobuf 4.22.1 on python 3.11; a long-running analysis tool that talks to multiple servers grows linearly with the amount of protobuf messaging, consuming all 16GB of RAM, then all swap space, then crashing the machine horribly.  If I disable upb, memory usage is flat for hours.  tracemalloc says there's never more than 40 to 50 MB of python objects in existence at any time, so the memory leak is outside of python's object space.

**Comment by tvalentyn** [comment]
cc: @haberman

**Comment by ericsalo** [comment]
The leak has been found and a patch is making its way through testing now.

**Comment by zhangskz** [comment]
@ericsalo Can you make sure this gets patched to 24.x so we can release it with our next set of fixes?

**Comment by ericsalo** [comment]
https://github.com/protocolbuffers/upb/pull/1521

**Comment by zhangskz** [comment]
Thanks Eric!
