### ISSUE TITLE
setting oneOfDef fields fails to be encoded

### ISSUE THREAD

**Issue by bjne** [protocolbuffers/upb#129]
``` lua
			upb.OneofDef{
				name = "function",
				fields = {
					upb.FieldDef{
						name = "function_name",
						number = 5,
						type = upb.TYPE_STRING
					},
					upb.FieldDef{
						name = "function_id",
						number = 6,
						type = upb.TYPE_INT32
					},
				}
			},
```

setting `msg.function_name = "foo" ` works fine, but when serializing it, foo is not in the message.
Is there any special way oneOf's should be set?

**Comment by haberman** [comment]
The Lua bindings are experimental and not currently supported, sorry. I've updated the README to reflect this. Hopefully someday the Lua bindings will be publicly available and fully supported!
