### ISSUE TITLE
Build error with C++20: bitwise operation between different enumeration types

### ISSUE THREAD

**Issue by phallot** [protocolbuffers/upb#1340]
When building with Clang-15 and std=c++20, quite a few warnings like the following are raised.  
Unfortunately, due to `-Werror`, this fails the build.

```
bazel-out/aarch64-opt/bin/external/envoy_api/envoy/admin/v3/config_dump_shared.upb.h:1578:97: error: bitwise operation between different enumeration types ('upb_FieldMode' and 'upb_LabelFlags') is deprecated [-Werror, -Wdeprecated-enum-enum-conversion]
  const upb_MiniTableField field = {5, UPB_SIZE(16, 4), 0, kUpb_NoSub, 5, kUpb_FieldMode_Scalar | kUpb_LabelFlags_IsAlternate | (kUpb_FieldRep_4Byte << kUpb_FieldRep_Shift)};
```

I don't know enough about the project to propose a fix, sorry. Maybe casting to the correct integral type?

**Comment by ericsalo** [comment]
A fix has just been pushed to the main branch so I'm closing this. Please let us know if the fix is insufficient.
