### ISSUE TITLE
lua binding  compile error

### ISSUE THREAD

**Issue by dhx1989** [protocolbuffers/upb#165]
try to run the lua bindings，i get:

undefined reference to `upb_fielddef_typeisset'

undefined reference to `lupb_checkfieldtype'
undefined reference to UPB_ASSERT/UNUSED

also some functions are only declared without definition
int luaopen_upb(lua_State *L);

**Comment by dhx1989** [comment]
@haberman  Can you help me?

**Comment by haberman** [comment]
I'm sorry for the slow response. The Lua bindings are not currently supported, they are internal-only (I've updated the README to reflect this). Hopefully someday they will be public and supported.
