### ISSUE TITLE
upb doesn't work with development build of Bazel

### ISSUE THREAD

**Issue by hlopko** [protocolbuffers/upb#172]
Howdy dear upb,

it seems the version check doesn't work with development builds of Bazel (e.g. https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/989#a4a2138e-0f8b-402d-92ff-0a9cf8c0845f). Currently Bazel returns empty string as version in this case. Because of this we see upb green with released version of Bazel, but red on our downstream pipeline.

Thanks!

**Comment by philwo** [comment]
FYI @haberman

**Comment by haberman** [comment]
I couldn't find a prerelease version of Bazel to test with, but hopefully this PR will do the trick: https://github.com/protocolbuffers/upb/pull/176

**Comment by meteorcloudy** [comment]
Ping~  Is this issue going to be fixed?

**Comment by haberman** [comment]
Should be fixed by https://github.com/protocolbuffers/upb/pull/258.

**Comment by meteorcloudy** [comment]
Thanks! I'll re-enable upd in Bazel downstream.
