### ISSUE TITLE
Please verify that --incompatible_depset_for_libraries_to_link_getter works

### ISSUE THREAD

**Issue by oquenchil** [protocolbuffers/upb#174]
upb appears broken on BazelCI due to a different reason so I cannot tell whether this incompatible flag will break it.

It's really easy to migrate. Please verify:
https://github.com/bazelbuild/bazel/issues/8118

**Comment by haberman** [comment]
upb is still working, so I think it was compatible with this. :)

Sorry for not getting back to you sooner.
