### ISSUE TITLE
JSON Well Known Type Parsing Question

### ISSUE THREAD

**Issue by warhammerkid** [protocolbuffers/upb#175]
I'm currently running into a problem where the previous ruby JSON encoding behavior was to write out well known types (like timestamp and duration) as normal messages like:

```json
{"time":{"seconds":1558627300,"nanos":18342000}}
```

Now that 3.7.0 has been released with updated parsing code this now triggers a parse error:

> Google::Protobuf::ParseError: Error occurred during parsing: Parse error at 'seconds":1558627300,"nanos":18342000}}'

Is this expected behavior?

From looking at the state machine as a novice with Ragel, I'm guessing that the `string` machine thinks it should parse the first member key as a timestamp instead of realizing that it's inside a new object context and should simply use `string_machine` for parsing, hence why it fails right at the beginning of the first key inside the timestamp.

**Comment by TeBoring** [comment]
The change is intended. According to our spec: https://developers.google.com/protocol-buffers/docs/proto3#json, timestamp should be like "1972-01-01T10:00:20.021Z"

**Comment by warhammerkid** [comment]
Sorry for the slow response. I'm aware that the change to the output behavior is intended, and that makes a lot of sense. However, I'm wondering if it's also intended that JSON clients *MUST* send timestamps as strings, rather than that they *MAY* send timestamps as strings, but can also send them formatted as normal messages.

We're using Envoyproxy for some of our gRPC services and it is able to decode message-style and string-style JSON into a timestamp, which is why this change in decoding behavior took me by surprise. If that permissive behavior is incorrect it would probably be worth mentioning to them.

**Comment by TeBoring** [comment]
Sorry for the inconvenience.
With upb’s current implementation, it’s a little difficult to support both
style. In the long term, we also just want to support one to make our code
easy to maintain.
