### ISSUE TITLE
Integrate upb with OSS-Fuzz

### ISSUE THREAD

**Issue by haberman** [protocolbuffers/upb#181]
https://github.com/google/oss-fuzz#accepting-new-projects

**Comment by Google-Autofuzz** [comment]
Did you mean "integrate upb with OSS-Fuzz" instead of Bloaty?

**Comment by haberman** [comment]
Whoops, yes I did! I have already integrated Bloaty, years ago now. :)

**Comment by Google-Autofuzz** [comment]
Hi,

UPB was [reverted](https://github.com/google/oss-fuzz/pull/2553#issuecomment-509300415) because it is completely broken for AFL and libFuzzer. If you have the time, can you take a look. 

It seems to fail at the following:

````
bazel build --verbose_failures --dynamic_mode=off --spawn_strategy=standalone \
  --genrule_strategy=standalone --strip=never \
  --copt=-fno-sanitize=vptr --linkopt=-fno-sanitize=vptr --define fuzz=true \
  --linkopt=-lc++ --linkopt=-pthread ${EXTRA_BAZEL_FLAGS} \
  ${BAZEL_BUILD_TARGETS[*]}
````

**Comment by haberman** [comment]
upb is currently part of OSS-Fuzz: https://github.com/google/oss-fuzz/tree/master/projects/upb
