### ISSUE TITLE
cmake build of upb library fails on Windows ("Need implementations of [v]snprintf and va_copy")

### ISSUE THREAD

**Issue by jtattermusch** [protocolbuffers/upb#189]
Encountered in this PR https://github.com/grpc/grpc/pull/19384 (which is blocked by this problem).

```
 T:\src\github\grpc\workspace_cpp_windows_x86_cmake\third_party\upb\.\upb/upb.h(71): fatal error C1189: #error:  Need implementations of [v]snprintf and va_copy [T:\src\github\grpc\workspace_cpp_windows_x86_cmake\cmake\build\third_party\upb\upb.vcxproj]

Full log is here: https://source.cloud.google.com/results/invocations/457c55ee-0a35-46d9-93cd-40e1472129f8/targets/github%2Fgrpc/tests
```

**Comment by jtattermusch** [comment]
@haberman  what fix do you suggest for https://github.com/protocolbuffers/upb/blob/fa88c6017ddb490aa78c57bea682193f533ed69a/upb/upb.h#L71?

**Comment by chwarr** [comment]
Take a look at #94: I got the CMake-based build working with MSVC (fixing this issue and a handful of others), but there's more work to be done around codegen.

**Comment by haberman** [comment]
@chwarr Feel free to send your changes as a PR, we can at least get the Windows part of it working even if the CMake part isn't fully ready to go.

**Comment by chwarr** [comment]
Recent commits by @veblush have added MSVC support to the CMake build. I think this can be closed now.
