### ISSUE TITLE
Build status links in README point to Google-internal page

### ISSUE THREAD

**Issue by alex-xnor** [protocolbuffers/upb#211]
The Ubuntu status link in the README, for example, points to <https://fusion.corp.google.com/projectanalysis/summary/KOKORO/prod%3Aupb%2Fubuntu%2Fcontinuous>. This page is not accessible to non-Googlers.

**Comment by haberman** [comment]
I've removed the broken links. The plan is to move to GitHub Actions, which will be accessible to anybody.
