### ISSUE TITLE
There are no "install" targets for in the CMakeLists.txt file.

### ISSUE THREAD

**Issue by coryan** [protocolbuffers/upb#215]
As it says in the description, I cannot see how your CMakeList.txt would be able to install the libraries and headers. Maybe your intention is to support this later?

**Comment by haberman** [comment]
Yes, at the moment I am wanting people to use upb from its source location only (through Bazel or by copying into their own source tree).

When the API (and possibly ABI) are more stable, I may revisit this decision.

**Comment by haberman** [comment]
The upb README is now more explicit that upb is not generally offered as a C library, as its API and ABI are not stable.

A few users such as gRPC do use upb's C API directly, and we will coordinate with them for any breakages. gRPC is not currently using upb's CMakeLists.txt directly, they are vendoring upb using their own build system to build it.

I am currently planning to remove upb's CMake build completely: https://github.com/protocolbuffers/upb/pull/408
