### ISSUE TITLE
upb_deps() zlib dependency breaks grpc as an external bazel repository

### ISSUE THREAD

**Issue by asraa** [protocolbuffers/upb#225]
Hi, 

I'm building gRPC in Envoyproxy as an external bazel repository. gRPC calls `grpc_deps()` and `grpc_extra_deps()` in their workspace. `grpc_extra_deps()` includes loading `upb_deps()`. However, Envoy independently uses zlib, and we run into a problem linking against two copies of the library. I run in to the error:
```
ERROR: /usr/local/google/home/asraa/.cache/bazel/_bazel_asraa/f23f95d44d486dfd95cb67d4d7eb464d/external/upb/bazel/workspace_deps.bzl:30:5: no such target '@com_google_protobuf//:third_party/zlib.BUILD': target 'third_party/zlib.BUILD' not declared in package ''; however, a source file of this name exists.  (Perhaps add 'exports_files(["third_party/zlib.BUILD"])' to /BUILD?) defined by /usr/local/google/home/asraa/.cache/bazel/_bazel_asraa/f23f95d44d486dfd95cb67d4d7eb464d/external/com_google_protobuf/BUILD and referenced by '//external:zlib'
```

I believe the problem is similar to https://github.com/protocolbuffers/protobuf/pull/5784. Would loading zlib if not existing in `upb_deps()` solve the issue?

Here is the reproducing code when importing gRPC 1.25.0 in to Envoy: https://github.com/envoyproxy/envoy/pull/8968

**Comment by haberman** [comment]
I believe this should be fixed by https://github.com/protocolbuffers/upb/pull/230. Please re-open if you are still experiencing the problem.
