### ISSUE TITLE
How do I build the protoc plugin?

### ISSUE THREAD

**Issue by ChristopherRabotin** [protocolbuffers/upb#237]
Hi there,
I've never used bazel before, and I'm failing to understand how to build the upb plugin for `protoc`. Could this be added to the README?

I assume it was possible back in August 2019 because an prior coworker left some documentation which starts with `protoc --plugin "$PROJDIR/upb/bazel-bin/protoc-gen-upb" ...` .

Bazel build doesn't find any target after cloning this repo:
```
$ bazel build 
INFO: Invocation ID: 99a859d2-b376-48da-b15d-286cc58997ee
INFO: Analysed 0 targets (0 packages loaded, 0 targets configured).
INFO: Found 0 targets...
INFO: Elapsed time: 0.072s, Critical Path: 0.00s
INFO: 0 processes.
INFO: Build completed successfully, 1 total action
```

I also can't seem to build specific sections of the `BUILD` file:
```
$ bazel run cc_test      
INFO: Invocation ID: 01184618-7909-40a0-ae5b-abfd5243f2a8
DEBUG: Rule 'bazel_skylib' modified arguments {"sha256": "efaa058f58c12579bc5cdc71cf19a56533e26e2b0a76799799efff21b6447850"}
ERROR: Skipping 'cc_test': no such target '//:cc_test': target 'cc_test' not declared in package '' (did you mean 'upb_test'?) defined by /home/chris/Workspace/upb/BUILD
WARNING: Target pattern parsing failed.
ERROR: no such target '//:cc_test': target 'cc_test' not declared in package '' (did you mean 'upb_test'?) defined by /home/chris/Workspace/upb/BUILD
INFO: Elapsed time: 0.046s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
FAILED: Build did NOT complete successfully (0 packages loaded)
```

**Comment by nicolasnoble** [comment]
bazel build :protoc-gen-upb

The resulting binary will be in the bazel-bin folder.

**Comment by nicolasnoble** [comment]
Also in general, `bazel build` doesn't do anything. You want `bazel build
:all` to build all known targets, or `bazel build ...` to build all known
targets and subtargets recursively.

**Comment by ChristopherRabotin** [comment]
Many thanks for the very quick reply. That worked.
