### ISSUE TITLE
What closure should string handler's "end" event receive?

### ISSUE THREAD

**Issue by martinmaly** [protocolbuffers/upb#24]
Scenario: Incremental JSON parsing and accumulating strings.
JSON parser vends out string values in pieces. When parsing JSON into in-memory representation the handler needs to be able to accumulate individual string pieces and finally end up with a single string value (alternative would be to accumulate string pieces into more complex data structure and use that in place of string but that would leak the internal details of JSON parsing into the rest of the application, and create tension elsewhere (such as simply passing this complex string to printf)).

With this goal in mind, how does one do that?

Say, I am parsing:

``` json
{ "foo": "this is a long string value vended in pieces" }
```

into C struct:

``` c
struct FromJson {
  char *foo;
}
```

To do so, we define 3 handlers:

``` c
// upb_startstr_handlerfunc
void *start_foo(void *c, const void *hd, size_t size_hint);
```
- allocates 'string builder'
- closure c == FromJson*
- returns closure that encapsulates the string builder

``` c
// upb_string_handlerfunc
size_t add_foo(void *c, const void *hd, const char *buf, size_t n, const upb_bufhandle* handle);
```
- appends to string builder
- closure c == string builder

``` c
// upb_endfield_handlerfunc
bool end_foo(void *c, const void *hd);
```
- creates a string literal from accumulated pieces and saves the result into FromJson::foo
- closure c == FromJson *

==> At this point, the end_foo handler lost track of the string builder and cannot populate the "foo" field with the reassembled string.

Workarounds:
- start_foo takes bigger closure which contains pointer to FromJson and additional state (current string builder)
- add_foo handler always maintains FromJson::foo in its final state (eliminating need for end_foo.

Proposal:
end_foo takes the same closure as add_foo, or both parent closure (FromJson *) and child closure (string builder)

**Comment by martinmaly** [comment]
This could be also string-specific solution where string uses its own "end" handler rather than using the one common to all field types.

**Comment by martinmaly** [comment]
Another option could be to change the string protocol slightly so that the "append string" handler takes indication that "this is the last string piece".

**Comment by haberman** [comment]
I think this is a pretty convincing argument that, at least given the current closure model, end handlers need the "sub" closure also.

The only way I see to accommodate this use case with the current model is: give the string builder a pointer directly to &FromJson.foo, and update the `char*` in place so it's a coherent string after every string buffer. But it's probably too onerous to *require* this model.

**Comment by haberman** [comment]
The experience of several years has convinced me that the "handlers" interface is too complicated. This bug is a great example of why. Tracking callbacks and closures is really complicated. For this reason, the newer upb APIs do not use callbacks/closures.
