### ISSUE TITLE
Build error with GCC10

### ISSUE THREAD

**Issue by Zantares** [protocolbuffers/upb#262]
Hi, I'm a TensorFlow developer from Intel, right now I want to build TF with GCC10(build from GCC master), and I got an error:
```
ERROR: /home/tenglu/.cache/bazel/_bazel_tenglu/06bd6985b04fd4452cd3ed1645f7a7cc/external/upb/BUILD:57:1: C++ compilation of rule '@upb//:upb' failed (Exit 1)
In file included from /usr/include/string.h:494,
                 from external/upb/upb/upb.h:16,
                 from external/upb/upb/upb.c:2:
In function 'strncpy',
    inlined from 'upb_status_seterrmsg' at external/upb/upb/upb.c:40:3:
/usr/include/x86_64-linux-gnu/bits/string_fortified.h:106:10: error: '__builtin_strncpy' specified bound 127 equals destination size [-Werror=stringop-truncation]
  106 |   return __builtin___strncpy_chk (__dest, __src, __len, __bos (__dest));
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors

```

Obviously GCC10 reported this warning as error by default. It can be simple fixed by using `memcpy` instead of `strncpy` here: https://github.com/protocolbuffers/upb/blob/master/upb/upb.c#L40 but I'm not sure if it will break any logic. Could someone help to confirm and fix this issue? Thanks!

**Comment by haberman** [comment]
Sorry for the delay on this. I think the warning is wrong, but I can write some code that GCC will be happier about. I'll send a PR for this tomorrow.

**Comment by Zantares** [comment]
> Sorry for the delay on this. I think the warning is wrong, but I can write some code that GCC will be happier about. I'll send a PR for this tomorrow.

Thanks for your fix!
BTW, how can I apply your commit in bazel? Does it enable automatically or need a version update?

**Comment by yongtang** [comment]
@Zantares In case you are working on building TF with gcc 10+, the PR #39470 will update upb.
