### ISSUE TITLE
Binary decoder needs a parameter for max depth.

### ISSUE THREAD

**Issue by aristotll** [protocolbuffers/upb#269]
https://github.com/protocolbuffers/protobuf/issues/6297  

I used the ruby protobuf which calls upb.

https://github.com/protocolbuffers/upb/blob/master/upb/pb/decoder.c

https://github.com/protocolbuffers/upb/blob/master/upb/pb/decoder.c#L971-L987

**Comment by haberman** [comment]
For upb itself, we need to add an options parameter to `upb_decode()` to let the user specify options. I'll retitle the bug to reflect this.

For Ruby protobuf, we'll also need to add an option to the Ruby decode method. Feel free to file a separate bug on the main protobuf repo for this.

**Comment by haberman** [comment]
Params we need for the decoder:

- max recursion depth
- copy vs. alias strings
- discard unknown fields?
- callback/closure for pull parser and/or stack/size for pull parser

**Comment by haberman** [comment]
upb has a decoder parameter for max depth now, so I'm closing this issue on the upb side. We should follow up with a change on the Ruby side to add this as an optional parameter to decode.
