### ISSUE TITLE
MSVC 2019 Fix Build

### ISSUE THREAD

**Issue by cfis** [protocolbuffers/upb#284]
Currently upb doesn't build with msvc 2019. I made a pull request to the protobuf ruby extension project to fix its local copy of upb.

The changes are at:

https://github.com/protocolbuffers/protobuf/pull/7521/commits/b69dc29578e19d27f71903e1ac0d9906a0520391

Happy to create a separate pull request if that would be helpful.

**Comment by haberman** [comment]
Thanks for the fixes! A PR here would be helpful too.

By the way, what was the compile failure that prompted you to fix `UPB_ASSUME()`?

**Comment by haberman** [comment]
I'm curious if it's similar to the error that inspired me to add `UPB_ASSUME()` to begin with:
https://github.com/protocolbuffers/upb/commit/a6c54729df861842705a2ed53d637c41d40a63bf

**Comment by cfis** [comment]
The specific errors are:

upb.c(6927): error C2059: syntax error: 'if'
upb.c(6931): error C2059: syntax error: 'if'
upb/json/parser.rl(389): error C2059: syntax error: 'if'
upb/json/parser.rl(414): error C2059: syntax error: 'if'
upb/json/parser.rl(2019): error C2059: syntax error: 'if'

If you expand the macro with the patch, then:

    UPB_ASSUME(ok);

Would become:
 do {} if (false && (ok))

And that isn't valid C code.

Note, according to http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2017/p0627r0.pdf the MSVC equivalent to GCC __builtin_unreachable is __assume(0)

**Comment by haberman** [comment]
Ah, it was meant to be:

```
#define UPB_ASSUME(expr) do {} while (false && (expr))
```

I should fix that so other non-GCC, non-MSVC platforms can compile correctly.

**Comment by cfis** [comment]
Ah that makes sense. Thanks for merging the commits. Do you want to leave this issue open as a reminder to fix UPB_ASSUME?
