### ISSUE TITLE
unable to build TF Serving because of error in upb

### ISSUE THREAD

**Issue by satishpasumarthi** [protocolbuffers/upb#300]
This issue popped up in recent release of TensorFlow serving 2.2. Corresponding issues on Google's TF Serving repo https://github.com/tensorflow/serving/issues/1642

Exact error while building serving from bazel:

ERROR: /root/.cache/bazel/_bazel_root/a64d7dba00d3b1f5dfea992b48914cc1/external/upb/BUILD:57:1: C++ compilation of rule '@upb//:upb' failed (Exit 1)
external/upb/upb/table.c: In function 'upb_inttable_pop':
external/upb/upb/table.c:588:10: error: 'val.val' may be used uninitialized in this function [-Werror=maybe-uninitialized]
return val;
^~~
cc1: all warnings being treated as errors
Target //tensorflow_serving/model_servers:tensorflow_model_server failed to build

**Comment by haberman** [comment]
Thanks for the report. I think that function can be removed.

**Comment by haberman** [comment]
This was fixed in #301.
