### ISSUE TITLE
Code generation ends up with permission error when bazel building with local spawn_strategy 

### ISSUE THREAD

**Issue by veblush** [protocolbuffers/upb#354]
Currently both upb_proto_library and upb_proto_reflection_library will create `*.upb.* file` and `*.upbdefs.*` file, which sometimes causes a permission error. (https://github.com/grpc/grpc/pull/24953#issuecomment-747880583) 

Can you make a change on code generator like?
- upb_proto_library only generates `*.upb.*`
- upb_proto_reflection_library only generates `*.upbdefs.*`

**Comment by haberman** [comment]
Wow, that sounds like some painful debugging you went through! Sorry for the trouble, I didn't know there was such a thing as a non-sandboxed build.

Yes, this should be pretty easy to change. I'll send out a PR in the next day or two?

**Comment by veblush** [comment]
@haberman Great and thanks! I'm looking forward to a PR 👍

**Comment by veblush** [comment]
@haberman Thanks for the quick fix. I verified that gRPC can be built now!
