### ISSUE TITLE
cleanup item: upb build badges are being downloaded from GCS bucket under grpc-testing project

### ISSUE THREAD

**Issue by jtattermusch** [protocolbuffers/upb#366]
This [GCS bucket](https://console.cloud.google.com/storage/browser/upb-kokoro-results) used for the .png build badges in README.md is located under the grpc-testing project (gRPC's testing infrastructure).

it would be good to move the build badges under a cloud project owned by the protobuf team. gRPC's testing infrastructure is  performing a cleanup and we can't guarantee we will support this bucket in the future.

**Comment by jtattermusch** [comment]
Btw this is what's been done for protocolbuffers/protobuf repository: https://github.com/protocolbuffers/protobuf/pull/8138

**Comment by haberman** [comment]
upb is no longer referencing build badges from its README.
