### ISSUE TITLE
building //upb/bindings/lua:lupb

### ISSUE THREAD

**Issue by bjne** [protocolbuffers/upb#368]
I am trying to experiment with the lua binding, but after running bazel build //upb/bindings/lua:lupb, and waiting 4 days for it to download 30% of the sourcecode on the internet and build the world from scratch, including java and whatever crap. I am not able to find any usable lupb.so library for lua, only:

```
Target //upb/bindings/lua:lupb up-to-date:
  bazel-bin/upb/bindings/lua/liblupb.a
  bazel-bin/upb/bindings/lua/liblupb.so
```

Is it supposed to be possible to build this at all?

**Comment by haberman** [comment]
The Lua bindings are mainly intended for internal use by upb itself (see: https://github.com/protocolbuffers/upb#lua-bindings). They are not intended for general use at this time.
