### ISSUE TITLE
Provide FFI-based LuaJIT bindings

### ISSUE THREAD

**Issue by DemiMarie** [protocolbuffers/upb#40]
In LuaJIT, calls to C functions made via the FFI are much faster than calls made via the classic Lua/C API.  FFI calls are as fast as a C call, while C API calls not only have the API overhead but disable the JIT compiler over the entire trace (before LuaJIT 2.1)/require a jump into the interpreter for each call (LuaJIT 2.1).

The one time where it is better to use the classic Lua/C API is when the C function may call back into Lua.  Calls into the Lua API from functions invoked via the FFI in the same Lua universe have undefined behavior, and calling LuaJIT FFI callbacks will cause a LuaJIT VM PANIC if the Lua code that called into C was compiled.  This requires that the JIT compiler be disabled over the entire trace containing the caller via `jit.off`.  On the other hand, LuaJIT 2.1 includes a trace stitching feature that allows for all code until the API call to be compiled, and for the code after the return of the C function to be compiled.

Additionally, binding a C function via the FFI is very simple.

**Comment by haberman** [comment]
If and when the upb Lua bindings are stable and publicly supported, I think this could be a very useful thing.

**Comment by haberman** [comment]
I'm not focused on providing upb as a public Lua protobuf implementation at the moment.

I have a prototype Lua implementation of protobuf in the source tree, but this is mainly to validate upb's C APIs and implementation, and to make it easier to test them.

I'm going to close this for now. If/when there is ever first-class Lua support, it would probably be in a separate project.
