### ISSUE TITLE
More unpredictable behavior on 32-bit builds

### ISSUE THREAD

**Issue by csmichael-as** [protocolbuffers/upb#415]
I'm on an x86_64 machine and encountering unpredictable behavior when compiling for 32-bit targets.  When I parse a protobuf  built for a 32-bit platform, my program segfaults but when I build it for a 64-bit target, everything works fine.

Below is the stack-trace:

0xe93720ae in decode_toarray (d=0xe9237018, 
    ptr=0xe89ff005 "\020\001\022/Christopher Rabotin <rabotin@advanced-space.com\032\a\b\345\017\020\b\030\004\"\b2021.8.42\326\004A conversion of de438.bsp planetary ephemerides.\n\nPlanetary Body: Sun", ' ' <repeats 17 times>, "\n\tXB Start Epoch: 2459504.5", ' ' <repeats 14 times>..., msg=0x0, submsgs=0xf02fcd38 <xb_Metadata_submsgs>, 
    field=0xf02eb200 <xb_Metadata__fields>, val=0xe9236dd8, op=6) at upb/upb/decode.c:413
413	  upb_array *arr = *arrp;
(gdb) bt
#0  0xe93720ae in decode_toarray (d=0xe9237018, 
    ptr=0xe89ff005 "\020\001\022/Christopher Rabotin <rabotin@advanced-space.com\032\a\b\345\017\020\b\030\004\"\b2021.8.42\326\004A conversion of de438.bsp planetary ephemerides.\n\nPlanetary Body: Sun", ' ' <repeats 17 times>, "\n\tXB Start Epoch: 2459504.5", ' ' <repeats 14 times>..., msg=0x0, submsgs=0xf02fcd38 <xb_Metadata_submsgs>, 
    field=0xf02eb200 <xb_Metadata__fields>, val=0xe9236dd8, op=6) at upb/upb/decode.c:413
#1  0xe937349b in decode_msg (d=0xe9237018, 
    ptr=0xe89ff005 "\020\001\022/Christopher Rabotin <rabotin@advanced-space.com\032\a\b\345\017\020\b\030\004\"\b2021.8.42\326\004A conversion of de438.bsp planetary ephemerides.\n\nPlanetary Body: Sun", ' ' <repeats 17 times>, "\n\tXB Start Epoch: 2459504.5", ' ' <repeats 14 times>..., msg=0x0, layout=0xf02fc910 <xb_Metadata_msginit>) at upb/upb/decode.c:670
#2  0xe9372dd9 in decode_tosubmsg (size=673, field=0xe937c260 <xb_XB__fields>, submsgs=0xe9382d94 <xb_XB_submsgs>, submsg=0x0, 
    ptr=0xe89ff003 "\n\002\020\001\022/Christopher Rabotin <rabotin@advanced-space.com\032\a\b\345\017\020\b\030\004\"\b2021.8.42\326\004A conversion of de438.bsp planetary ephemerides.\n\nPlanetary Body: Sun", ' ' <repeats 17 times>, "\n\tXB Start Epoch: 2459504.5", ' ' <repeats 12 times>..., d=0xe9237018) at upb/upb/decode.c:375
#3  decode_tomsg (d=0xe9237018, 
    ptr=0xe89ff003 "\n\002\020\001\022/Christopher Rabotin <rabotin@advanced-space.com\032\a\b\345\017\020\b\030\004\"\b2021.8.42\326\004A conversion of de438.bsp planetary ephemerides.\n\nPlanetary Body: Sun", ' ' <repeats 17 times>, "\n\tXB Start Epoch: 2459504.5", ' ' <repeats 12 times>..., msg=0xe938471c <_libxbc_buf+28>, submsgs=0xe9382d94 <xb_XB_submsgs>, 
    field=0xe937c260 <xb_XB__fields>, val=0xe9236f88, op=6) at upb/upb/decode.c:562
#4  0xe9373519 in decode_msg (d=0xe9237018, 
    ptr=0xe89ff003 "\n\002\020\001\022/Christopher Rabotin <rabotin@advanced-space.com\032\a\b\345\017\020\b\030\004\"\b2021.8.42\326\004A conversion of de438.bsp planetary ephemerides.\n\nPlanetary Body: Sun", ' ' <repeats 17 times>, "\n\tXB Start Epoch: 2459504.5", ' ' <repeats 12 times>..., msg=0xe938471c <_libxbc_buf+28>, layout=0xe9382a80 <xb_XB_msginit>)
    at upb/upb/decode.c:676
#5  0xe93738b4 in decode_top (d=0xe9237018, 
    buf=0xe89ff000 "\n\241\005\n\002\020\001\022/Christopher Rabotin <rabotin@advanced-space.com\032\a\b\345\017\020\b\030\004\"\b2021.8.42\326\004A conversion of de438.bsp planetary ephemerides.\n\nPlanetary Body: Sun", ' ' <repeats 17 times>, "\n\tXB Start Epoch: 2459504.5         "..., msg=0xe938471c <_libxbc_buf+28>, l=0xe9382a80 <xb_XB_msginit>) at upb/upb/decode.c:719
#6  0xe9373a9b in _upb_decode (
    buf=0xe89ff000 "\n\241\005\n\002\020\001\022/Christopher Rabotin <rabotin@advanced-space.com\032\a\b\345\017\020\b\030\004\"\b2021.8.42\326\004A conversion of de438.bsp planetary ephemerides.\n\nPlanetary Body: Sun", ' ' <repeats 17 times>, "\n\tXB Start Epoch: 2459504.5         "..., size=227762, msg=0xe938471c <_libxbc_buf+28>, l=0xe9382a80 <xb_XB_msginit>, extreg=0x0, 
    options=0, arena=0xede846e4 <_libxbc_buf+78643172>) at upb/upb/decode.c:758
#7  0xe936fe0e in upb_decode (
    buf=0xe89ff000 "\n\241\005\n\002\020\001\022/Christopher Rabotin <rabotin@advanced-space.com\032\a\b\345\017\020\b\030\004\"\b2021.8.42\326\004A conversion of de438.bsp planetary ephemerides.\n\nPlanetary Body: Sun", ' ' <repeats 17 times>, "\n\tXB Start Epoch: 2459504.5         "..., size=227762, msg=0xe938471c <_libxbc_buf+28>, l=0xe9382a80 <xb_XB_msginit>, 
    arena=0xede846e4 <_libxbc_buf+78643172>) at ./upb/upb/decode.h:59
#8  0xe936fe8e in xb_XB_parse (
    buf=0xe89ff000 "\n\241\005\n\002\020\001\022/Christopher Rabotin <rabotin@advanced-space.com\032\a\b\345\017\020\b\030\004\"\b2021.8.42\326\004A conversion of de438.bsp planetary ephemerides.\n\nPlanetary Body: Sun", ' ' <repeats 17 times>, "\n\tXB Start Epoch: 2459504.5         "..., size=227762, arena=0xede846e4 <_libxbc_buf+78643172>) at src/bindings/xb.upb.h:59
#9  0xe936fff0 in xbc_load (file=0xe937b19e "/cf/plan_eph.exb", xb=0xe93835d4 <_xb>, ckhsum=0) at src/xbc.c:54

**Comment by haberman** [comment]
Sorry I just saw this. Do you have a repro for this crash?
