### ISSUE TITLE
how to use protoc-gen-lua?

### ISSUE THREAD

**Issue by RPG3D** [protocolbuffers/upb#466]
any doc about protoc-gen-lua and lupb API?

**Comment by haberman** [comment]
I added a note in the README for the Lua directory: https://github.com/protocolbuffers/upb/tree/main/upb/bindings/lua

> These are some bare-bones upb bindings for Lua.
>
> These bindings exist primarily for experimentation and testing. They are incomplete and are not really intended for use in any application. This is by no means a complete or supported protobuf library.
