### ISSUE TITLE
Streaming decoding in amalgation files

### ISSUE THREAD

**Issue by fsaintjacques** [protocolbuffers/upb#467]
I'm wondering if the amalgated `upb.{h,c}` contain the functionality to partially decode messages (and register descriptors). I have this project in mind where I would like to re-implement https://github.com/rgov/sqlite_protobuf but using upb. The TLDR is to implement a function that given a byte payload, a message name in the registry and a field's path (or field mask), extract the given field.

**Comment by fsaintjacques** [comment]
@haberman, gentle ping.

**Comment by haberman** [comment]
upb does not support any kind of streaming decoding. Previous versions of upb did support this, but the streaming interfaces were complicated and under-performing.

upb probably isn't the best match for what you're trying to do, sorry about that. If you wanted you could always prune the schema to just the messages and fields that you care about, but ultimately I think it's going to be simpler and faster to operate on the wire format yourself.
