### ISSUE TITLE
Add upb_Arena_BytesAllocated()

### ISSUE THREAD

**Issue by haberman** [protocolbuffers/upb#528]
An arena should be capable of reporting how many bytes have been allocated from the underlying allocator:

```c
size_t upb_Arena_BytesAllocated(const upb_Arena* arena)
```

1. We will need to add a `bytes_allocated` member [`upb_Arena`](https://github.com/protocolbuffers/upb/blob/main/upb/upb_internal.h#L36): 
1. This number only changes when the arena allocates an underlying block, *not* on every `upb_Arena_Malloc()`.
1. I think that `upb_Arena_Fuse()` should not add the `bytes_allocated` fields together, otherwise we would double-count.

**Comment by zhangskz** [comment]
Per #9546, this is obsolete since dsize doesn't actually get us what we wanted. We have an alternative way to allow Ruby to understand how much memory is allocated.
