### ISSUE TITLE
Need method to reuse arena!

### ISSUE THREAD

**Issue by calvin2021y** [protocolbuffers/upb#547]
I need a function to release all object create from arena, but keep the arena object not to destroyed.

This is for avoid memory allocation/free for every small  RESTful  request,  after response send all related object is not used but reuse the arena in next request.

**Comment by fowles** [comment]
Perhaps you are looking for [Arena::Reset](https://cs.github.com/protocolbuffers/protobuf/blob/4b0871e2053534aa96cbc5a7c45f23486d2cab52/src/google/protobuf/arena.h#L372).  

Word of warning about the design you are looking at if your requests have a variance in memory usage, this will cause every arena in your pool to eventually reach the large end of that variance which will raise your programs total memory consumption quite a bit.  You would be well advised to keep stats on the size of your arenas and only reuse arenas below the 60th percentile in size.

**Comment by fowles** [comment]
Oh this, is upb not the full protobuf my mistake

**Comment by fowles** [comment]
The presence of `fuse` operations makes this harder.  Such an API would have to be fallible, it would be something like `Arena* TryReset(Arena*)` that returns `NULL` on failure.

**Comment by haberman** [comment]
You could use a stateful custom allocator:

```c
   // MyAllocator caches freed blocks instead of returning them
   // to the OS. It is shared from request to request.
   MyAllocator alloc;
   MyAllocator_Init(&alloc);

  // The arena is per-request, but it obtains blocks from the caching
  // allocator. So you can avoid malloc()/free().
  upb_Arena* arena = upb_Arena_New(NULL, 0, &alloc);

  // allocate object...

  // When you free the arena, the blocks are returned to the allocator
  // but the allocator will not release them to the OS.
  upb_Arena_Free(arena);

  // At application shutdown, you can destroy your allocator
  // to finally return your blocks to the OS.
  MyAllocator_Destroy(&alloc);
```

**Comment by calvin2021y** [comment]
@haberman 

With current design this is not posiable, because MyAllocator don't know the size of the block to free.

```c
UPB_INLINE void upb_free(upb_alloc* alloc, void* ptr) {
  assert(alloc);
  alloc->func(alloc, ptr, 0, 0);
}
```

**Comment by calvin2021y** [comment]
@haberman

I am not sure there is a workaround for this,  if not we may need reopen this issue, or should I create a new one ?

**Comment by haberman** [comment]
If we changed this line to directly invoke the allocator, passing the block size as `old_size`, would that give you what you need?

https://github.com/protocolbuffers/upb/blob/be7dfeba6bdd4891bb3854c120fe579d43327501/upb/upb.c#L268

**Comment by calvin2021y** [comment]
Yes, with old_size pass to allocator will fix the problem.
