### ISSUE TITLE
68bc62a7fa5febbf5c8ab2fe8f6171121d18690f likely to break user code

### ISSUE THREAD

**Issue by mbarbon** [protocolbuffers/upb#63]
Specifically,

https://github.com/google/upb/commit/68bc62a7fa5febbf5c8ab2fe8f6171121d18690f#diff-cb3a8d4ce81fefbdf9810d0e9dc4e27cR251

makes the size of upb_table dependent on whether NDEBUG is defined, and since upb_table is used in inline functions, this will break user code unless it is compiled with the same NDEBUG value as the library (and at the moment the Makefile unconditionally defines NDEBUG.

The specific use case I ended up debugging is sink->StartString() calling upb_sink_startstr() in sink.h which then retrieves the wrong value for startstr() (because it has the wrong offset for upb_handler::table) and crashes.

**Comment by haberman** [comment]
You're absolutely right, I'm sorry I haven't fixed this before now. upb should not change the size of any structs defined in `.h` files based on `NDEBUG`. This needs to be fixed.

**Comment by haberman** [comment]
None of the upb headers mention NDEBUG anymore.
