### ISSUE TITLE
It is unclear whether encoders/decoders can be reused

### ISSUE THREAD

**Issue by mbarbon** [protocolbuffers/upb#65]
Hi,
in my implementation, I am currently reusing a single encoder/decoder, allocated at startup time.

This works well for the pb encoder/decoder, but fails with a parse error for the JSON decoder. looking at the source code, it looks like the state machine is never re-initialized. I'm not sure if this is a bug (I can provide a patch for it) or a documentation issue and encoders/decoders are not supposed to be re-used (I can provide a patch as well).

Thanks!
Mattia

**Comment by haberman** [comment]
I'm very sorry for the very late reply. The JSON decoder doesn't currently support any kind of "reset" method that would allow reusing the decoder object. Such a thing could conceivably be added.

However these old handlers-based interfaces are semi-deprecated. Over many years I came to the conclusion that they are too complicated. So I probably won't be investing too much into enhancing these interfaces.
