### ISSUE TITLE
Parsing *.proto files supported?

### ISSUE THREAD

**Issue by vadimkantorov** [protocolbuffers/upb#71]
I am looking to assess if upb is a good fit for parsing Caffe's neural net [models](https://github.com/BVLC/caffe/blob/master/src/caffe/proto/caffe.proto) directly from Torch / Lua.

Do I understand correctly that parsing of *.proto files from Lua isn't supported at the moment?

Thanks,
Vadim

**Comment by vadimkantorov** [comment]
`th tools/upbc.lua caffe.proto` fails with `Invalid wire  type`

**Comment by haberman** [comment]
That's correct -- parsing .proto files directly isn't supported right now. `upbc` only works on compiled descriptors. You have to run the .proto file through `protoc` to get a compiled descriptor, then run `upbc` on the output.

To answer your question though, you are looking for a protobuf API to use from Lua? That support is currently very spotty, but I'm working right now on providing much more complete support for protobufs in Lua.

**Comment by vadimkantorov** [comment]
Thanks for the information !
 
Yes, I was looking for a protobuf message parser in lua to load Caffe models without resorting to python or c++ protobuf bindings. If I could drop the dependency on protobuf and parse *.proto directly, that would be a nice bonus !

**Comment by haberman** [comment]
I think parsing of .proto files in upb is unlikely to happen anytime soon, sorry!
