### ISSUE TITLE
How to translate Message in lua to Protocol Buffers in C?

### ISSUE THREAD

**Issue by magicminglee** [protocolbuffers/upb#72]
Hi, I want to use upb in my project. Currently, upb can decode google Protocol Buffers in lua, but  can't serialize Protocol Buffers. I want to construct a upb's Message in lua and pass that to C. When passing, upb's Message in lua is a userdata in C. That is puzzled for me that how can i change this userdata to Protocol Buffers. And by the way, how long to  achieve serializing Protocol Buffers in lua. I'm looking forward to get your reply. Thanks very much.

**Comment by haberman** [comment]
I'm very sorry for this very late reply. The Lua bindings are experimental and not yet supported. I've updated the README to reflect this. Hopefully someday they will be fully supported.
