### ISSUE TITLE
upb is broken on Bazel CI (latest release Bazel, Linux only)

### ISSUE THREAD

**Issue by Wyverald** [protocolbuffers/upb#760]
Example breakage: https://buildkite.com/bazel/upb/builds/1235#0182f140-e79a-40af-80c7-844e49d722ad

Apparently this is because of some fuzzing tests needing rules_python, which in turn has some error about a Python import being missing. (Our image uses Python 3.6.9.)

**Comment by perezd** [comment]
Is this a problem on your end? We recently updated to the latest published rules_python which was necessary for us:
https://github.com/bazelbuild/rules_python/releases/tag/0.11.0

I did notice they just pushed 0.12.0, is that preferred?

**Comment by Wyverald** [comment]
I honestly have no idea. If rules_python doesn't work with Python 3.6.9, that may be a bug on their side. You could try upgrading to 0.12.0 and see if that fixes the build; if not, we'll need to disable upb on Bazel CI until this is fixed.

**Comment by Wyverald** [comment]
You're completely right. However, it's up to each project to own the CI setup themselves; the Bazel team has no bandwidth to ensure all projects using Bazel having passing builds.

**Comment by perezd** [comment]
I've opened an issue with rules_python to see if they can provide guidance.

**Comment by Wyverald** [comment]
Thanks! To be clear, it's not clear to me whether the upgrade to rules_python 0.10.0 was the trigger for this breakage; upb was broken for [a different reason](https://github.com/protocolbuffers/upb/pull/738) prior to that so we haven't had a green build in a while (actually ever, but that's a long story...)

**Comment by perezd** [comment]
I think it's pretty likely, let's see what they say.

**Comment by perezd** [comment]
FWIW, in this PR: Bazel works/is passing here:
https://github.com/protocolbuffers/upb/pull/761

**Comment by Wyverald** [comment]
The rules_python issue confirmed that the root cause is Python 3.6.9 EOL. We can fix that on our end.

Thanks for helping resolve this!
