### ISSUE TITLE
Incorrect validation of optional fields in 'extends' blocks

### ISSUE THREAD

**Issue by bezmax** [protocolbuffers/upb#812]
Upb has implemented [validation](https://github.com/protocolbuffers/upb/blob/main/upb/reflection/field_def.c#L654-L658) to ensure that the descriptor matches the newer `one-of` [implementation of optional fields](https://github.com/protocolbuffers/protobuf/blob/main/docs/implementing_proto3_presence.md) in proto3.

However, the optional fields inside `extends` clauses are encoded differently, and protoc does not generate synthetic one-of for those. For this reason, when upb tries to read a descriptor containing this sort of optional field - it throws the error.

For example, upb is unable to read the descriptor generated from [this example from official protobuf documentation](https://developers.google.com/protocol-buffers/docs/proto#customoptions).

I am not familiar with upb code structure, therefore sorry for somewhat messy example. Here's how I tested:

https://github.com/bezmax/upb/commit/192f9b2c1cd7e91e3341f5423b708ebf5e38a2b5

Then:

```
bazel build //:test_cpp
bazel test //:test_cpp
```

Output:
```
exec ${PAGER:-/usr/bin/less} "$0" || exit 1
Executing tests from //:test_cpp
-----------------------------------------------------------------------------
Running main() from gmock_main.cc
[==========] Running 6 tests from 1 test suite.
[----------] Global test environment set-up.
[----------] 6 tests from Cpp
[ RUN      ] Cpp.Iteration
Error loading compiled-in descriptor for file 'upb/test_cpp.proto' (this should never happen): field with proto3_optional was not in a oneof (upb.test.my_option)
```

**Comment by haberman** [comment]
Confirmed, upb should not require a synthetic oneof for extension fields. More info: https://github.com/protocolbuffers/protobuf/issues/8234#issuecomment-774224376

@ericsalo can you take a look?

**Comment by ericsalo** [comment]
On it.

**Comment by ericsalo** [comment]
Fixed and pushed.
