### ISSUE TITLE
Visual Studio build

### ISSUE THREAD

**Issue by dkrikun** [protocolbuffers/upb#94]
Please add Visual Studio compatible build.

**Comment by haberman** [comment]
I would like upb to have CMake support. I think this is the best way to get a Visual Studio build.

I'm not sure yet when CMake support will happen. It is tricky especially because of how protos are generated at compile time with the upb compiler.

**Comment by chwarr** [comment]
I have the CMake-based build compiling cleanly with VS 2019. It doesn't look like the tests are hooked into CMake yet, so I don't know if it actually works properly.

Is this enough forward progress for a PR, or should tests also pass too?

**Comment by haberman** [comment]
Unfortunately I'm not sure how useful that will be in practice without code generation. upb needs generated code for your input protos. The code generation is the harder part to get working with CMake.

**Comment by haberman** [comment]
upb has a CMake build now.
